# Generated by Django 5.1.3 on 2024-11-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('fullname', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('classname', models.CharField(choices=[('7.1', '7.1'), ('7.2', '7.2'), ('7.3', '7.3'), ('8.1', '8.1'), ('8.2', '8.2'), ('8.3', '8.3'), ('9.1', '9.1'), ('9.2', '9.2'), ('9.3', '9.3')], max_length=20, verbose_name='کلاس')),
                ('joined_number', models.PositiveBigIntegerField(unique=True, verbose_name='شماره عضویت')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
