# Generated by Django 5.1.3 on 2025-08-16 15:25

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_scoreentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreentry',
            name='date',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='reason',
            field=models.CharField(max_length=255),
        ),
    ]
